import defaultPoster from '../images/default-poster.jpg';


const moviesTest = [
  {
    "_id": "1",
    "poster": defaultPoster,
    "title": "33 слова о дизайне-1",
    "duration": "1ч 42м",
    "saved": false,
  },
  {
    "_id": "2",
    "poster": defaultPoster,
    "title": "33 слова о дизайне-1",
    "duration": "1ч 42м",
    "saved": false,
  },
  {
    "_id": "3",
    "poster": defaultPoster,
    "title": "33 слова о дизайне-1",
    "duration": "1ч 42м",
    "saved": false,
  },
  {
    "_id": "4",
    "poster": defaultPoster,
    "title": "33 слова о дизайне-1",
    "duration": "1ч 42м",
    "saved": true,
  },
  {
    "_id": "5",
    "poster": defaultPoster,
    "title": "33 слова о дизайне-1",
    "duration": "1ч 42м",
    "saved": true,
  },
  {
    "_id": "6",
    "poster": defaultPoster,
    "title": "33 слова о дизайне-1",
    "duration": "1ч 42м",
    "saved": true,
  },
  {
    "_id": "7",
    "poster": defaultPoster,
    "title": "33 слова о дизайне-1",
    "duration": "1ч 42м",
    "saved": true,
  },
  {
    "_id": "8",
    "poster": defaultPoster,
    "title": "33 слова о дизайне-1",
    "duration": "1ч 42м",
    "saved": true,
  },
  {
    "_id": "9",
    "poster": defaultPoster,
    "title": "33 слова о дизайне-1",
    "duration": "1ч 42м",
    "saved": true,
  },
  {
    "_id": "10",
    "poster": defaultPoster,
    "title": "33 слова о дизайне-1",
    "duration": "1ч 42м",
    "saved": true,
  },
  {
    "_id": "12",
    "poster": defaultPoster,
    "title": "33 слова о дизайне-1",
    "duration": "1ч 42м",
    "saved": true,
  },
  {
    "_id": "13",
    "poster": defaultPoster,
    "title": "33 слова о дизайне-1",
    "duration": "1ч 42м",
    "saved": true,
  },
  {
    "_id": "14",
    "poster": defaultPoster,
    "title": "33 слова о дизайне-1",
    "duration": "1ч 42м",
    "saved": true,
  },
  {
    "_id": "15",
    "poster": defaultPoster,
    "title": "33 слова о дизайне-1",
    "duration": "1ч 42м",
    "saved": true,
  },
  {
    "_id": "16",
    "poster": defaultPoster,
    "title": "33 слова о дизайне-1",
    "duration": "1ч 42м",
    "saved": true,
  },
  {
    "_id": "17",
    "poster": defaultPoster,
    "title": "33 слова о дизайне-1",
    "duration": "1ч 42м",
    "saved": true,
  },
  {
    "_id": "18",
    "poster": defaultPoster,
    "title": "33 слова о дизайне-1",
    "duration": "1ч 42м",
    "saved": true,
  },
]

export default moviesTest
